### PR TITLE
Change automatically the category

### PR DESCRIPTION
**Pull request by pherjung**
I'm not sure it's the right way, but here a proposition to set automatically the right category. A review is required as I'm not familiar at all with QML/JS.

### CODE REVIEW

**Comment by nephros** [comment]
Nice idea, thank you.

I think I'd want some changes, will look over it tomorrow.

**Comment by pherjung** [comment]
Is there a reason why this line appears twice:
```
if (bugInfo.ssu.domain == 'cbeta') postCategory = config.submit.category_cbeta;
```

**Comment by nephros** [comment]
Fat fingered it. Fixed now.

**Review by nephros — APPROVED** [review]

**Comment by pherjung** [comment]
I tested on a device with the latest stable version and it doesn't work as expected :(

If cbeta is enabled, `bugInfo.ssu.domain` will return `cbeta` too. The aim is to change the category only if the device is running an unstable version.

**Comment by nephros** [comment]
> I tested on a device with the latest stable version and it doesn't work as expected :(
> 
> If cbeta is enabled, `bugInfo.ssu.domain` will return `cbeta` too. The aim is to change the category only if the device is running an unstable version.

So you're saying your device is registered for cbeta, but you have not updated it? Rather a special case, but I'll look into adding an additional check for this.

**Comment by nephros** [comment]
Something like fe720faa06028c4a?

**Comment by pherjung** [comment]
Looks good. Ideally a solution without modifying the variable `latest` at every release should be better. I'll create an separate issue for that.

**Pull request merged**
